#!/bin/bash

# if no argument is passed, we run the sbcl version from the submodule of the repository in which this script reside.
[ -z "$*" ] && 

# Absolute path to this script. /home/user/bin/foo.sh
SCRIPT=$(readlink -f $0)
# Absolute path this script is in. /home/user/bin
SCRIPTPATH=$(dirname $SCRIPT)
PROJECT_ROOT=$SCRIPTPATH/../..

if [ -z "$*" ]; then
    echo -e "\nTrying to run SBCL from the submodule of the repository
in which this script reside. Pass an argument to specify another location.
Valid values are 'root' (opt this if SBCL is installed as root) or
a username for a user with SBCL installed in its home directory."
   SBCL_BIN=$PROJECT_ROOT/sbcl/bin/sbcl
   SBCL_HOME=$PROJECT_ROOT/sbcl/lib/sbcl
   SBCL_CORE="--core $SBCL_HOME/sbcl.core"
else
# an argument is passed with the user name.
  if [ "$1" = "root" ]; then
      SBCL_BIN=sbcl
  else
      USER=$1
      HOME=/home/$USER
      [ ! -d "$HOME" ] && echo "The user does not exist." && exit;
  fi
fi

SWANK_PORT=4005
WEBLOCKS_PORT=8080
echo "Project root: $PROJECT_ROOT"
$SBCL_BIN $SBCL_CORE --userinit $PROJECT_ROOT/webapp/primarvarden.sbclrc $PROJECT_ROOT/webapp/ $WEBLOCKS_PORT $SWANK_PORT --no-linedit
