#!/bin/bash

# Absolute path to this script. /home/user/bin/foo.sh
SCRIPT=$(readlink -f $0)
# Absolute path this script is in. /home/user/bin
SCRIPTPATH=$(dirname $SCRIPT)
PROJECT_ROOT=$SCRIPTPATH/../..

# no args: run SBCL from repo with the invoking user
usage(){
    echo -e "Usage: $0 username 
no args: Passing no args, SBCL is run from the submodule of the repository
in which this script reside.
1st arg: username (e.g. 'root' requires SBCL installed as root)"
}

usage;

if [ -z "$*" ]; then
   SBCL_BIN=$PROJECT_ROOT/sbcl/bin/sbcl
   SBCL_HOME=$PROJECT_ROOT/sbcl/lib/sbcl
   SBCL_CORE="--core $PROJECT_ROOT"/sbcl/lib/sbcl/sbcl.core
else
# an argument is passed with the user name.
  if [ "$1" = "root" ]; then
      SBCL_BIN=sbcl
  else
      USER=$1
      HOME=/home/$USER
      [ ! -d "$HOME" ] && echo "The user does not exist." && exit;
      [ -z "$SBCL_HOME" ] && echo "The environment variable SBCL_HOME is not defined." && exit;
  fi
fi

SWANK_PORT=4005
WEBLOCKS_PORT=8080
echo "Project root: $PROJECT_ROOT"
$SBCL_BIN $SBCL_CORE --userinit $PROJECT_ROOT/webapp/primarvarden.sbclrc $PROJECT_ROOT/webapp/ $WEBLOCKS_PORT $SWANK_PORT --no-linedit
